const teamData = {
  "FC Bayern München": { name: "FC Bayern München", logo: "https://upload.wikimedia.org/wikipedia/commons/8/8d/FC_Bayern_M%C3%BCnchen_logo_%282024%29.svg", color: "#dc052d" },
  "Borussia Dortmund": { name: "Borussia Dortmund", logo: "https://upload.wikimedia.org/wikipedia/commons/6/67/Borussia_Dortmund_logo.svg", color: "#fce200" },
  "RB Leipzig": { name: "RB Leipzig", logo: "https://upload.wikimedia.org/wikipedia/commons/d/d6/VEREINFACHTES_LOGO_-_RB_Leipzig.svg", color: "#c8102e" },
  "Bayer Leverkusen": { name: "Bayer Leverkusen", logo: "https://upload.wikimedia.org/wikipedia/de/f/f7/Bayer_Leverkusen_Logo.svg", color: "#e32219" },
  "VfB Stuttgart": { name: "VfB Stuttgart", logo: "https://upload.wikimedia.org/wikipedia/commons/e/eb/VfB_Stuttgart_1893_Logo.svg", color: "#e60000" },
  "Eintracht Frankfurt": { name: "Eintracht Frankfurt", logo: "https://upload.wikimedia.org/wikipedia/de/3/32/Logo_Eintracht_Frankfurt_1998.svg", color: "#e40c2b" },
  "TSG Hoffenheim": { name: "TSG Hoffenheim", logo: "https://upload.wikimedia.org/wikipedia/commons/e/e7/Logo_TSG_Hoffenheim.svg", color: "#005ca9" },
  "1. FC Heidenheim": { name: "1. FC Heidenheim", logo: "https://upload.wikimedia.org/wikipedia/commons/9/9d/1._FC_Heidenheim_1846.svg", color: "#20408f" },
  "Werder Bremen": { name: "Werder Bremen", logo: "https://upload.wikimedia.org/wikipedia/commons/b/be/SV-Werder-Bremen-Logo.svg", color: "#1a8f43" },
  "SC Freiburg": { name: "SC Freiburg", logo: "https://upload.wikimedia.org/wikipedia/de/b/bf/SC_Freiburg_Logo.svg", color: "#000000" },
  "FC Augsburg": { name: "FC Augsburg", logo: "https://upload.wikimedia.org/wikipedia/de/b/b5/Logo_FC_Augsburg.svg", color: "#b52829" },
  "VfL Wolfsburg": { name: "VfL Wolfsburg", logo: "https://upload.wikimedia.org/wikipedia/commons/f/f3/Logo-VfL-Wolfsburg.svg", color: "#65af1f" },
  "Borussia Mönchengladbach": { name: "Borussia Mönchengladbach", logo: "https://upload.wikimedia.org/wikipedia/commons/8/81/Borussia_M%C3%B6nchengladbach_logo.svg", color: "#000000" },
  "1. FC Union Berlin": { name: "1. FC Union Berlin", logo: "https://upload.wikimedia.org/wikipedia/commons/4/44/1._FC_Union_Berlin_Logo.svg", color: "#d40511" },
  "1. FSV Mainz 05": { name: "1. FSV Mainz 05", logo: "https://upload.wikimedia.org/wikipedia/commons/9/9e/Logo_Mainz_05.svg", color: "#c30c0e" },
  "1. FC Köln": { name: "1. FC Köln", logo: "https://upload.wikimedia.org/wikipedia/commons/0/01/1._FC_Koeln_Logo_2014%E2%80%93.svg", color: "#ed1c24" },
  "FC St. Pauli": { name: "FC St. Pauli", logo: "https://upload.wikimedia.org/wikipedia/commons/b/b3/Fc_st_pauli_logo.svg", color: "#472727" },
  "Hamburger SV": { name: "Hamburger SV", logo: "https://upload.wikimedia.org/wikipedia/commons/f/f7/Hamburger_SV_logo.svg", color: "#0f2650" },
};
