const logoMap = {
  "FC Bayern München": "https://upload.wikimedia.org/wikipedia/commons/1/1f/FC_Bayern_München_logo_(2024).svg",
  "Borussia Dortmund": "https://upload.wikimedia.org/wikipedia/de/6/67/Borussia_Dortmund_logo.svg",
  "RB Leipzig": "https://upload.wikimedia.org/wikipedia/commons/7/7e/VEREINFACHTES_LOGO_-_RB_Leipzig.svg",
  "Bayer Leverkusen": "https://upload.wikimedia.org/wikipedia/de/8/80/Bayer_Leverkusen_Logo.svg",
  "VfB Stuttgart": "https://upload.wikimedia.org/wikipedia/de/8/8e/VfB_Stuttgart_1893_Logo.svg",
  "Eintracht Frankfurt": "https://upload.wikimedia.org/wikipedia/commons/d/d4/Logo_Eintracht_Frankfurt_1998.svg",
  "TSG Hoffenheim": "https://upload.wikimedia.org/wikipedia/commons/4/49/Logo_TSG_Hoffenheim.svg",
  "1. FC Heidenheim": "https://upload.wikimedia.org/wikipedia/commons/5/5a/1._FC_Heidenheim_1846.svg",
  "Werder Bremen": "https://upload.wikimedia.org/wikipedia/commons/b/be/SV-Werder-Bremen-Logo.svg",
  "SC Freiburg": "https://upload.wikimedia.org/wikipedia/commons/f/f1/SC_Freiburg_Logo.svg",
  "FC Augsburg": "https://upload.wikimedia.org/wikipedia/commons/8/89/Logo_FC_Augsburg.svg",
  "VfL Wolfsburg": "https://upload.wikimedia.org/wikipedia/commons/4/4c/Logo-VfL-Wolfsburg.svg",
  "Borussia Mönchengladbach": "https://upload.wikimedia.org/wikipedia/commons/8/81/Borussia_Mönchengladbach_logo.svg",
  "1. FC Union Berlin": "https://upload.wikimedia.org/wikipedia/commons/e/e4/1._FC_Union_Berlin_Logo.svg",
  "1. FSV Mainz 05": "https://upload.wikimedia.org/wikipedia/commons/5/5c/Logo_Mainz_05.svg",
  "1. FC Köln": "https://upload.wikimedia.org/wikipedia/commons/5/53/1._FC_Koeln_Logo_2014–.svg",
  "FC St. Pauli": "https://upload.wikimedia.org/wikipedia/commons/7/70/Fc_st_pauli_logo.svg",
  "Hamburger SV": "https://upload.wikimedia.org/wikipedia/commons/6/66/Hamburger_SV_logo.svg"
};